py_binary(
    name = "check-exe-have-no-ext",
    srcs = ["check-exe-have-no-ext.py"],
    deps = [":files"],
)

py_binary(
    name = "check-script-permissions",
    srcs = ["check-script-permissions.py"],
    deps = [":files"],
)

py_binary(
    name = "check-python3-black",
    srcs = ["check-python3-black.py"],
    deps = [":files"],
)

py_binary(
    name = "check-python3-flake8",
    srcs = ["check-python3-flake8.py"],
    deps = [":files"],
)

py_binary(
    name = "check-shell-shfmt",
    srcs = ["check-shell-shfmt.py"],
    deps = [":files"],
)

py_library(
    name = "files",
    srcs = ["files.py"],
)

