py_binary(
    name = "check-exe-have-no-ext",
    srcs = ["check-exe-have-no-ext.py"],
)

py_binary(
    name = "check-script-permissions",
    srcs = ["check-script-permissions.py"],
)

py_binary(
    name = "lint-python3-black",
    srcs = ["lint-python3-black.py"],
)

py_binary(
    name = "lint-python3-flake8",
    srcs = ["lint-python3-flake8.py"],
)

py_binary(
    name = "lint-shell",
    srcs = ["lint-shell.py"],
)
